#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/README.html#stages
#
stages:
  - build
  - deploy

build-job:
  stage: build
  tags:
    - ibcmb
  script:
    - mvn -DskipTests=true clean package
  only:
    - cmb_final_dev2


deploy-job:
  stage: deploy
  tags:
    - ibcmb
  script:
    - sudo mv /opt/tomcat/latest/webapps/ROOT /opt/tomcat/latest/webapps/ROOT_${CI_JOB_ID}
    - sudo mkdir /opt/tomcat/latest/webapps/ROOT
    - sudo cp  ${PWD}/target/ibcmb.war /opt/tomcat/latest/webapps/ROOT
    - sudo jar -xf ibcmb.war
  only:
  - cmb_final_dev2


