stages:
  - build
  - deploy

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2  -DskipTests=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"

build-job:
  stage: build
  tags:
    - ibcmb
  script:
    - mvn clean package
    - sudo mv /opt/tomcat/gtl/webapps/ROOT /opt/tomcat/gtl/backup/ROOT_${CI_JOB_ID} || echo "No ROOT to backup"
    - sudo mkdir /opt/tomcat/gtl/webapps/ROOT
    - sudo unzip target/ibanking.war -d /opt/tomcat/gtl/webapps/ROOT
    - sudo /opt/tomcat/stl/bin/catalina.sh stop -force || echo "Tomcat not started"
    - sudo /opt/tomcat/stl/bin/catalina.sh start
  artifacts:
    paths:
      - target/*.war
  when:
    manual
