stages:
  - build
  - deploy

build_app:
  stage: build
  script: 
  - mvn clean package

deploy:
  stage: deploy
  dependencies:
    - build_app
  script:
    - mv /opt/tomcat/latest/webapps/ROOT /opt/tomcat/latest/webapps/ROOT$COMMIT_TIME
    - mkdir /opt/tomcat/latest/webapps/ROOT
    - cp target/ibcmb.war /opt/tomcat/latest/webapps/ROOT
    - jar -xf ibcmb.war
only:
    - cmb_final_dev2
