#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/README.html#stages
#

stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - mvn clean package


deploy-job:
  stage: deploy
  script:
    - echo "This job runs in the deploy stage."
    - echo "It only runs when both jobs in the test stage complete successfully"
