stages:
  - build
  - deploy

before_script:
  - export COMMIT_TIME=$(git show -s --format=%ct $CI_COMMIT_SHA)   

build:
  stage: build
  script: ./mvn clean package
  artifacts:
    paths:
      - target/ibcmb.war

production:
  stage: deploy
  script:
    - mv /opt/tomcat/latest/webapps/ROOT /opt/tomcat/latest/webapps/ROOT$COMMIT_TIME
    - mkdir /opt/tomcat/latest/webapps/ROOT
    - ./cp target/ibcmb.war /opt/tomcat/latest/webapps/ROOT
    - jar -xf ibcmb.war

  only:
    - cmb_final_dev
