#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/README.html#stages
#
stages:
  only:
  - cmb_final_dev2
  - build
  - deploy

build-job:
  stage: build
  script:
    - mvn clean package


deploy-job:
  stage: deploy
  script:
    - mv /opt/tomcat/latest/webapps/ROOT /opt/tomcat/latest/webapps/ROOT$COMMIT_TIME
    - mkdir /opt/tomcat/latest/webapps/ROOT
    - cp target/ibcmb.war /opt/tomcat/latest/webapps/ROOT
    - jar -xf ibcmb.war


