#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/README.html#stages
#
stages:
  - build
  - deploy

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2  -DskipTests=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"

build-job:
  stage: build
  tags:
    - ibcmb
  script:
    - mvn clean package
    - sudo mv /opt/tomcat/gtl/webapps/ROOT /opt/tomcat/gtl/webapps/ROOT_${CI_JOB_ID} || echo "No ROOT to backup"
    - sudo mkdir /opt/tomcat/gtl/webapps/ROOT
    - sudo unzip target/ibcmb.war -d /opt/tomcat/gtl/webapps/ROOT
  artifacts:
    paths:
      - target/*.war
  only:
    - icon_deploy


