
package com.expertedge.entrustplugin.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EntrustMultiFactorAuthImpl", targetNamespace = "http://ws.entrustplugin.expertedge.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EntrustMultiFactorAuthImpl {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pingEntrustConn", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PingEntrustConn")
    @ResponseWrapper(localName = "pingEntrustConnResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PingEntrustConnResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/pingEntrustConnRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/pingEntrustConnResponse")
    public String pingEntrustConn();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.expertedge.entrustplugin.ws.AuthResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performTokenAuth", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformTokenAuth")
    @ResponseWrapper(localName = "performTokenAuthResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformTokenAuthResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performTokenAuthRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performTokenAuthResponse")
    public AuthResponseDTO performTokenAuth(
            @WebParam(name = "arg0", targetNamespace = "")
                    TokenAuthDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.expertedge.entrustplugin.ws.AuthResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performTokenAuthCorporateNoCategory", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformTokenAuthCorporateNoCategory")
    @ResponseWrapper(localName = "performTokenAuthCorporateNoCategoryResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformTokenAuthCorporateNoCategoryResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performTokenAuthCorporateNoCategoryRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performTokenAuthCorporateNoCategoryResponse")
    public AuthResponseDTO performTokenAuthCorporateNoCategory(
            @WebParam(name = "arg0", targetNamespace = "")
                    TokenAuthCorporateDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.expertedge.entrustplugin.ws.AuthResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performPasswordAuth", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformPasswordAuth")
    @ResponseWrapper(localName = "performPasswordAuthResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformPasswordAuthResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performPasswordAuthRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performPasswordAuthResponse")
    public AuthResponseDTO performPasswordAuth(
            @WebParam(name = "arg0", targetNamespace = "")
                    PasswordAuthDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.expertedge.entrustplugin.ws.AdminResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performCreateEntrustUser", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformCreateEntrustUser")
    @ResponseWrapper(localName = "performCreateEntrustUserResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformCreateEntrustUserResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performCreateEntrustUserRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performCreateEntrustUserResponse")
    public AdminResponseDTO performCreateEntrustUser(
            @WebParam(name = "arg0", targetNamespace = "")
                    UserAdminDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.expertedge.entrustplugin.ws.AdminResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performDeleteEntrustUser", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformDeleteEntrustUser")
    @ResponseWrapper(localName = "performDeleteEntrustUserResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformDeleteEntrustUserResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performDeleteEntrustUserRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performDeleteEntrustUserResponse")
    public AdminResponseDTO performDeleteEntrustUser(
            @WebParam(name = "arg0", targetNamespace = "")
                    UserDelAdminDTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.expertedge.entrustplugin.ws.AuthResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "performTokenAuthNoCategory", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformTokenAuthNoCategory")
    @ResponseWrapper(localName = "performTokenAuthNoCategoryResponse", targetNamespace = "http://ws.entrustplugin.expertedge.com/", className = "com.expertedge.entrustplugin.ws.PerformTokenAuthNoCategoryResponse")
    @Action(input = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performTokenAuthNoCategoryRequest", output = "http://ws.entrustplugin.expertedge.com/EntrustMultiFactorAuthImpl/performTokenAuthNoCategoryResponse")
    public AuthResponseDTO performTokenAuthNoCategory(
            @WebParam(name = "arg0", targetNamespace = "")
                    TokenAuthDTO arg0);

}
